openapi: 3.0.0
info:
  x-skaffolder-id-project: 5ef073181024335abc55effa
  title: Test
  description: You can obtain JWT token from login API
  version: 0.1
servers:
  - url: http://localhost:3000/api
    description: Local server for testing
paths:
  /login:
    post:
      x-skaffolder-ignore: true
      summary: Login API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: admin
                password: 62f264d7ad826f02a8af714c0a54b197935b717656b80461686d450f7b3abde4c553541515de2052b9af70f710f0cd8a1a2d3f4d60aa72608d71a63a9a93c0f5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /verifyToken:
    post:
      x-skaffolder-ignore: true
      summary: Verify token API
      security: []
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /changePassword:
    post:
      x-skaffolder-ignore: true
      summary: Change password API
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                passwordNew:
                  type: string
                passwordOld:
                  type: string
      responses:
        "200":
          description: OK
  /dailyreport:
    post:
      x-skaffolder-id: 5ef076e01024335abc55f087
      x-skaffolder-name: create
      x-skaffolder-id-resource: 5ef076931024335abc55f07a
      x-skaffolder-resource: DailyReport
      x-skaffolder-crudAction: create
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION create
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION create
      tags:
        - DailyReport
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DailyReport"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Breakfast:
                  type: number
                CreatedDate:
                  type: integer
                Notes:
                  type: string
    get:
      x-skaffolder-id: 5ef076e01024335abc55f08b
      x-skaffolder-name: list
      x-skaffolder-id-resource: 5ef076931024335abc55f07a
      x-skaffolder-resource: DailyReport
      x-skaffolder-crudAction: list
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION list
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION list
      tags:
        - DailyReport
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DailyReport"
  "/dailyreport/{id}":
    delete:
      x-skaffolder-id: 5ef076e01024335abc55f08a
      x-skaffolder-name: delete
      x-skaffolder-id-resource: 5ef076931024335abc55f07a
      x-skaffolder-resource: DailyReport
      x-skaffolder-crudAction: delete
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION delete
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION delete
      tags:
        - DailyReport
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id: 5ef076e01024335abc55f084
      x-skaffolder-name: get
      x-skaffolder-id-resource: 5ef076931024335abc55f07a
      x-skaffolder-resource: DailyReport
      x-skaffolder-crudAction: get
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION get
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION get
      tags:
        - DailyReport
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DailyReport"
    post:
      x-skaffolder-id: 5ef076e01024335abc55f086
      x-skaffolder-name: update
      x-skaffolder-id-resource: 5ef076931024335abc55f07a
      x-skaffolder-resource: DailyReport
      x-skaffolder-crudAction: update
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION update
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION update
      tags:
        - DailyReport
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DailyReport"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DailyReport"
  "/user/{id}/changePassword":
    post:
      x-skaffolder-id: 5ef0731a1024335abc55f00b
      x-skaffolder-name: changePassword
      x-skaffolder-id-resource: 5ef073191024335abc55f004
      x-skaffolder-resource: User
      x-skaffolder-crudAction: 
      x-skaffolder-crudType: 
      x-skaffolder-description: Change password of user from admin
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: object
      x-skaffolder-url: /{id}/changePassword
      x-skaffolder-roles:
        - 5ef0731a1024335abc55f006
      summary: Change password of user from admin
      tags:
        - User
      responses:
        "200":
          description: OK
  /user:
    post:
      x-skaffolder-id: 5ef0731a1024335abc55f00a
      x-skaffolder-name: create
      x-skaffolder-id-resource: 5ef073191024335abc55f004
      x-skaffolder-resource: User
      x-skaffolder-crudAction: create
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION create
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION create
      tags:
        - User
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mail:
                  type: string
                name:
                  type: string
                password:
                  type: string
                roles:
                  type: string
                surname:
                  type: string
                username:
                  type: string
    get:
      x-skaffolder-id: 5ef0731a1024335abc55f007
      x-skaffolder-name: list
      x-skaffolder-id-resource: 5ef073191024335abc55f004
      x-skaffolder-resource: User
      x-skaffolder-crudAction: list
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION list
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION list
      tags:
        - User
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  "/user/{id}":
    delete:
      x-skaffolder-id: 5ef0731a1024335abc55f00e
      x-skaffolder-name: delete
      x-skaffolder-id-resource: 5ef073191024335abc55f004
      x-skaffolder-resource: User
      x-skaffolder-crudAction: delete
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION delete
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION delete
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id: 5ef0731a1024335abc55f008
      x-skaffolder-name: get
      x-skaffolder-id-resource: 5ef073191024335abc55f004
      x-skaffolder-resource: User
      x-skaffolder-crudAction: get
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION get
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION get
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    post:
      x-skaffolder-id: 5ef0731a1024335abc55f00c
      x-skaffolder-name: update
      x-skaffolder-id-resource: 5ef073191024335abc55f004
      x-skaffolder-resource: User
      x-skaffolder-crudAction: update
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION update
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION update
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    DailyReport:
      x-skaffolder-id: 5ef076931024335abc55f07a
      x-skaffolder-id-db: 5ef073181024335abc55effb
      x-skaffolder-id-entity: 5ef076931024335abc55f074
      x-skaffolder-url: /dailyreport
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        Breakfast:
          type: number
          x-skaffolder-id-attr: 5ef076931024335abc55f076
          x-skaffolder-type: Number
          x-skaffolder-enumeration:
            - All
            - Half
            - None
        CreatedDate:
          type: integer
          x-skaffolder-id-attr: 5ef076df1024335abc55f081
          x-skaffolder-type: Date
          x-skaffolder-required: true
        Notes:
          type: string
          x-skaffolder-id-attr: 5ef076931024335abc55f075
          x-skaffolder-type: String
          x-skaffolder-required: true
          x-skaffolder-unique: true
      x-skaffolder-relations:
        CreatedBy:
          x-skaffolder-id: 5ef076df1024335abc55f082
          x-skaffolder-type: m:m
          x-skaffolder-required: true
          x-skaffolder-ent1: 5ef076931024335abc55f074
          x-skaffolder-ent2: 5ef073181024335abc55effc
      required:
        - _id
        - CreatedDate
        - Notes
    User:
      x-skaffolder-id: 5ef073191024335abc55f004
      x-skaffolder-id-db: 5ef073181024335abc55effb
      x-skaffolder-id-entity: 5ef073181024335abc55effc
      x-skaffolder-url: /user
      x-skaffolder-type: User
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        mail:
          type: string
          x-skaffolder-id-attr: 5ef073181024335abc55f000
          x-skaffolder-type: String
        name:
          type: string
          x-skaffolder-id-attr: 5ef073181024335abc55f001
          x-skaffolder-type: String
        password:
          type: string
          x-skaffolder-id-attr: 5ef073181024335abc55efff
          x-skaffolder-type: String
          x-skaffolder-required: true
        roles:
          type: string
          x-skaffolder-id-attr: 5ef073181024335abc55f003
          x-skaffolder-type: String
        surname:
          type: string
          x-skaffolder-id-attr: 5ef073181024335abc55f002
          x-skaffolder-type: String
        username:
          type: string
          x-skaffolder-id-attr: 5ef073181024335abc55effe
          x-skaffolder-type: String
          x-skaffolder-required: true
      x-skaffolder-relations: 
      required:
        - _id
        - password
        - username
  x-skaffolder-db:
    - x-skaffolder-id: 5ef073181024335abc55effb
      x-skaffolder-name: Test_db
  x-skaffolder-page:
    - x-skaffolder-id: 5ef076e01024335abc55f083
      x-skaffolder-name: DailyReportEdit
      x-skaffolder-url: /dailyreports/{id}
      x-skaffolder-template: Edit_Crud
      x-skaffolder-resource: 5ef076931024335abc55f07a
      x-skaffolder-services:
        - 5ef076e01024335abc55f087
        - 5ef076e01024335abc55f086
        - 5ef076e01024335abc55f084
        - 5ef0731a1024335abc55f007
      x-skaffolder-nesteds:
        - 5ef076e01024335abc55f089
      x-skaffolder-links:
        - 5ef076e01024335abc55f089
      x-skaffolder-roles: []
    - x-skaffolder-id: 5ef076e01024335abc55f089
      x-skaffolder-name: DailyReportList
      x-skaffolder-url: /dailyreports
      x-skaffolder-template: List_Crud
      x-skaffolder-resource: 5ef076931024335abc55f07a
      x-skaffolder-services:
        - 5ef076e01024335abc55f08a
        - 5ef076e01024335abc55f08b
        - 5ef076e01024335abc55f08b
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 5ef076e01024335abc55f083
        - 5ef076e01024335abc55f089
      x-skaffolder-roles: []
    - x-skaffolder-id: 5ef073181024335abc55effd
      x-skaffolder-name: Home
      x-skaffolder-url: /home
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
      x-skaffolder-links:
        - 5ef076e01024335abc55f089
      x-skaffolder-roles: []
  x-skaffolder-roles: 
    - x-skaffolder-id: 5ef0731a1024335abc55f006
      x-skaffolder-name: ADMIN
